#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
# local: /etc/grub.d/40_custom
# windows_10 dev/sda3

menuentry "Windows 10 (bootloader) (dev/sda3)" {
	      set root='(hd0,1)'
	      chainloader +1
}
